# Generated by Django 5.2.5 on 2025-08-19 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('rubro', models.CharField(choices=[('super', 'Supermercado'), ('kiosco', 'Kiosco'), ('verduleria', 'Verdulería'), ('resto', 'Restaurante')], max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('etiqueta', models.CharField(choices=[('por_vencer', 'Por vencer'), ('excedente', 'Excedente')], max_length=20)),
                ('precio_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_oferta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('pickup_start', models.DateTimeField()),
                ('pickup_end', models.DateTimeField()),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='marketplace.partner')),
            ],
        ),
    ]
