# Generated by Django 5.2.5 on 2025-09-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='rubro',
        ),
        migrations.AddField(
            model_name='partner',
            name='categoria',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('verduleria', 'Verdulería'), ('supermercado', 'Supermercado'), ('cafe', 'Café & Deli'), ('kiosco', 'Kiosco')], default='restaurante', max_length=20),
        ),
    ]
