# Generated by Django 5.2.5 on 2025-09-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_partner_rubro_partner_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='packs/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='partners/'),
        ),
    ]
