# Generated by Django 5.2.1 on 2025-10-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_partner_short_description_partner_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
    ]
