# Generated by Django 5.2.1 on 2025-10-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_partner_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_decremented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='categoria',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('verduleria', 'VerdulerÃ\xada'), ('supermercado', 'Supermercado'), ('cafe', 'CafÃ© & Deli'), ('kiosco', 'Kiosco')], default='restaurante', max_length=20),
        ),
    ]
