# Generated by Django 5.2.1 on 2025-10-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_order_paid_at_order_stock_decremented_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='metodo_pago',
            field=models.CharField(choices=[('mp', 'Mercado Pago'), ('efectivo', 'Efectivo al retirar'), ('transferencia', 'Transferencia bancaria')], default='mp', max_length=20),
        ),
    ]
